### ISSUE TITLE
example of parsing nginx conf 

### ISSUE THREAD

**Issue by originnets** [nilium/codf#23]
How do I resolve

server
  {
    listen 80;
    server_name 127.0.0.1;
    index index.html index.htm;

    root  /home/wwwroot/ZWBShop/domain/zwbstore/web;
    include /aaa.conf;

    #error_page
    location ~ /ErrorPages/(400|401|403|404|405|502|503)\.html$
      {
        root /home/wwwroot/ZWBShop/domain/zwbstore/web;
      }

    location ~ .*\.php$
      {
        fastcgi_pass  unix:/tmp/aa.sock;
        fastcgi_index index.php;
        include fcgi.conf;
        fastcgi_param DOCUMENT_ROOT  web;
        fastcgi_param SCRIPT_FILENAME  /web$fastcgi_script_name;
      }

    location ~ .*\.(gif|jpg|jpeg|png|bmp|swf|flv|mp3|wma)$
      {
        expires      30d;
      }

    location ~ .*\.(js|css)$
      {
        expires      12h;
      }

    access_log off; #access_log end
    error_log /dev/null; #error_log end
  }

**Comment by nilium** [comment]
Have not seen this issue before now, but there's insufficient information here to respond to anything, so going to close it.
